import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";

const initialState = {
  // biến check xem người dùng đã đăng nhập hay chưa
  isAuthenticated: false,
  isLoading: true,
  user: {
    address: "",
    avatar: "",
    date_of_birth: "",
    email: "",
    full_name: "",
    id: "",
    phone_number: "",
    role: "",
  },
};

export const accountSlide = createSlice({
  name: "account",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    doLoginAction: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.isAuthenticated = true;
      state.isLoading = false;
      state.user = action.payload;
    },
    doGetAccountAction: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.isAuthenticated = true;
      state.isLoading = false;
        // console.log(action.payload)
      state.user = action.payload;
    },

    doUpdateAccountAction: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.isAuthenticated = true;
      state.isLoading = false;
        // console.log(action.payload)
      state.user.full_name = action.payload.full_name;
      state.user.phone_number = action.payload.phone_number;
      state.user.address = action.payload.address;
      state.user.date_of_birth = action.payload.date_of_birth;
    },
    
    doLogoutAction: (state, action) => {
      localStorage.removeItem("access_token");
      state.isAuthenticated = false;
      state.user = {
        address: "",
        avatar: "",
        date_of_birth: "",
        email: "",
        full_name: "",
        id: "",
        phone_number: "",
        role: "",
      };
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const { doLoginAction, doGetAccountAction, doLogoutAction ,doUpdateAccountAction} =
  accountSlide.actions;

export default accountSlide.reducer;
